spring:
  application:
    name: itoken-spring-cloud-zuul-feign
  zipkin:
    base-url: http://192.168.1.11:8768
  boot:
    admin:
      client:
        url: http://192.168.1.11:8769

server:
  port: 8764


eureka:
  client:
    service-url:
      defalutZone: http://192.168.1.11:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: itoken-spring-cloud-web-admin-feign