spring:
  application:
    name: itoken-spring-cloud-eureka
  zipkin:
    base-url: http://192.168.1.11:8769
  boot:
    admin:
      client:
        url: http://192.168.1.11:8770

server:
  port: 8761

eureka:
  instance:
    hostname: 192.168.1.11
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/