spring:
  application:
    name: itoken-spring-cloud-service-admin
  zipkin:
    base-url: http://192.168.1.11:8769
  boot:
    admin:
      client:
        url: http://192.168.1.11:8770

server:
  port: 8762

eureka:
  client:
    service-url:
      defalutZone: http://192.168.1.11:8761/eureka/