spring:
  application:
    name: itoken-spring-cloud-web-admin-feign
  zipkin:
    base-url: http://192.168.1.11:8768
  boot:
    admin:
      client:
        url: http://192.168.1.11:8769

server:
  port: 8763


eureka:
  client:
    service-url:
      defalutZone: http://192.168.1.11:8761/eureka/
feign:
  hystrix:
    enabled: true